import { CollectionConfig } from 'payload'
import slugify from 'slugify'

export const Modules: CollectionConfig = {
  slug: 'modules',
  fields: [
    { name: 'title', type: 'text', required: true },
    {
      name: 'slug',
      label: 'Slug (This is Autogenerated)',

      type: 'text',
      required: true,
      hooks: {
        beforeValidate: [
          ({ value, data }) => {
            if (value) return slugify(value, { lower: true, strict: true })
            if (data?.title) return slugify(data.title, { lower: true, strict: true })
            return value
          },
        ],
      },
    },
    { name: 'description', type: 'textarea' },
    { name: 'course', type: 'relationship', relationTo: 'courses', required: true },
    { name: 'orderIndex', type: 'number' },
    {
      name: 'lessons',
      type: 'relationship',
      relationTo: 'lessons',
      hasMany: true,
    },
    {
      name: 'unlockCondition',
      type: 'select',
      options: ['sequential', 'allPreviousComplete', 'instructorUnlock', 'dateUnlock'],
    },
    { name: 'unlockDate', type: 'date' },
    { name: 'isPublished', type: 'checkbox', defaultValue: false },
  ],
}
